spring.application.name=apoio-api

# URL de conexão (localhost no WSL geralmente é o padrão)
spring.datasource.url=jdbc:postgresql://localhost:5433/apoio_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# O 'update' cria as tabelas automaticamente com base nas classes Java que vamos criar
spring.jpa.hibernate.ddl-auto=update

# Para ver no console o SQL que o Hibernate está gerando (Ótimo para aprender!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false